[package]
name = "void-n-cluster"
version = "0.1.0"
edition = "2021"
exclude = [ "noise.png" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
rand_core = { version = "0.6.4", features = [ "getrandom" ] }
