[package]
name = "blue-noise-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
void-n-cluster = { path = "../../" }
rand = "0.8.5"